Add multiline shape
pyglet/pyglet pull request #1054
Opened 2024-02-25 14:46 UTC by Burnberry

General line shape consisting of multiple line segments by giving multiple point coordinates.

- Reuses _get_segement (also used in BezierCurve)
- Doesn't have contains implemented

Example:
![image](https://github.com/pyglet/pyglet/assets/107309423/c50538f5-b44a-4a7b-b95c-28faebbf6b69)

2024-02-25 19:30 UTC, pushfoo requested changes
At first glance, this seems to look good. However, could you please add this shape to unit tests?

If I remember correctly, most standard shape behavior should be covered by adding an entry here:
https://github.com/pyglet/pyglet/blob/4c4336c6431e9f2ddc94a4a04e6630194404e665/tests/unit/shapes/test_shapes.py#L8-L25

2024-02-26 14:12 UTC, Burnberry commented
Done and all tests passed

2024-02-27 07:11 UTC, benmoran56 approved these changes

2024-02-27 07:12 UTC, merged

2024-02-27 07:13 UTC, benmoran56 commented
Also, since this is a standalone addition, you could make another PR targeting the master branch. We can get it in the next point release sooner. The development branch is for the upcoming pyglet 2.1.