typo in examples directory
pyglet/pyglet pull request #303
Opened 2020-11-14 16:12 UTC by samlaf

Also... I can't find the graphics.py module anywhere. (not in version 1.5.9 either, which the latest docs point to)

2020-11-15 14:01 UTC, benmoran56 commented
Thanks for the PR. We recently reorganized things into subfolders, since the examples folder was getting a bit messy. 

It might be best to just point it towards the simple Hello World example, like: 
```py
python examples/hello_world.py
```

2020-11-16 00:27 UTC, benmoran56 requested changes
How about updating it to use `examples/hello_world.py` instead? That might make more sense anyway.

2020-11-16 15:45 UTC, samlaf reviewed
done

2020-11-17 00:17 UTC, benmoran56 approved these changes
Thanks, perfect!

2020-11-17 00:18 UTC, merged