Add Type Hints to image/__init__.py
pyglet/pyglet pull request #818
Opened 2023-04-30 22:19 UTC by gran4

I wanted to fix https://github.com/pyglet/pyglet/issues/787 so I type hinted it.

2023-05-01 00:04 UTC, gran4 commented
NOT done

2023-05-09 01:09 UTC, benmoran56 requested changes
Most of this looks good, but there are a large amount of inaccuracies. I have made comments for those that I have found, but there could be more.

2023-05-09 01:09 UTC, benmoran56 commented on pyglet/image/__init__.py
> +    """
Please leave this one as it was, with the leading """ on the same line.

2023-05-09 01:09 UTC, benmoran56 commented on pyglet/image/__init__.py
> +    def get_image_data(self) -> TextureRegion:
This return type is wrong. Should be ImageData.

2023-05-09 01:09 UTC, benmoran56 commented on pyglet/image/__init__.py
> +    def __getitem__(self, index: int) -> None:
The return type here is certainly not None. It will be either a single `AbstractImage` or a list of `AbstractImage`.

2023-05-24 08:57 UTC, benmoran56 requested changes

2023-05-24 08:57 UTC, benmoran56 commented on pyglet/image/__init__.py
> +    def save(self, filename: Optional[str]=None,
Two things: 
`filename` should not default to `None`. This is a bug. Filename is required. 
This function does not return anything, so return type should be `-> None`.

2023-05-24 08:57 UTC, benmoran56 commented on pyglet/image/__init__.py
> +        :rtype: None or bytes
:rtype: and :return: are not needed, because they are implied by the typing definitions.

2023-05-24 08:57 UTC, benmoran56 commented on pyglet/image/__init__.py
> +        :Parameters:
I would remove this section as it's unneeded.
It's also incorrect, as (x, y, z) is the destination, not the anchor point.

2023-05-24 08:57 UTC, benmoran56 commented on pyglet/image/__init__.py
> +    def set_data(self, fmt: str, pitch: int, data: Sequence[Union[bytes, str]]):
`data` should just be `bytes` here, not bytes/str.

2023-05-24 08:57 UTC, benmoran56 commented on pyglet/image/__init__.py
> -    region_class = None  # Set to TextureRegion after it's defined
Lets leave these local variables as they are. I don't see much benefit from typing information here, as they're internal defaults. It just adds more clutter, IMO.

2023-05-24 08:57 UTC, benmoran56 commented on pyglet/image/__init__.py
> +        :Parameters:
This can be removed. It's also incorrect - (x, y, z) do not mean the anchor points.

2023-05-25 04:30 UTC, gran4 commented
Ok. Are you the only one reviewing pyglet PRs.

On Wed, May 24, 2023 at 2:03 AM Benjamin ***@***.***> wrote:

> Pardon the delay, but it's quite challenging to review this PR. There are
> many mistakes, and it takes a lot of time to review manually. I added a few
> more comments for issues that I found. There are also several issues that
> appear all throughout, but I did not comment them.
>
>    1.
>
>    Many of the classmethods are wrong. cls should be the actual object of
>    the class that will be returned, but it's often shown as AbstractImage.
>    This might pass a type checker, but it's returning the subclass is more
>    accurate.
>    2.
>
>    There are many unnecessary docstring breaks. All docstrings should
>    start on the same line as the triple quotes for compactness. For example:
>
> def function():
>     """This is preferreddef function():    """
>     Not this
>
>
>    1. Many functions are unnecessarily wrapped. pyglet adheres to PEP8,
>    with the exception of a relaxed line length limit. It's acceptable (and
>    preferred) to allow function definitions to reach 100 (or up to 110)
>    columns, rather than splitting to multiple lines.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pyglet/pyglet/pull/818#issuecomment-1560727336>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ATHLIH7HGS5QINI6F3FVYDDXHXFFZANCNFSM6AAAAAAXRGF2NM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-09-16 00:33 UTC, closed without merging