Attempts to add Type hints to Clock
pyglet/pyglet pull request #855
Opened 2023-05-28 00:07 UTC by gran4

Something is probably wrong

2023-05-28 23:13 UTC, pushfoo commented
> Can the library typing_extensions be added to pyglet?

tl;dr I've also asked about it and been told no. It's annoying, but there are good reasons for it.

Banning mandatory external dependencies improves portability and eliminates a lot of potential problems, including upstream license or requirement changes breaking the project. For example, arcade had to drop 3.7 support early because a crucial dependency forced us to.

I asked about using typing_extensions [last year](https://discord.com/channels/438622377094414346/477394331112701952/1006813955685089370):

> pushfoo — 08/10/2022 2:39 AM
> I think -> Vec2 technically works for mypy 
> I wish I didn't check the PEP listing though
> knowing that the Self annotation exists makes me want to use the typing backports > module 
> https://github.com/python/typing_extensions
> Benjamin — 08/10/2022 2:41 AM
> unfortunately, external dependencies are a deal-breaker for pyglet.

[Additional details](https://discord.com/channels/438622377094414346/477394331112701952/1006815338446475294):
> Benjamin — 08/10/2022 2:44 AM
pyglet actually doesn't have any dependencies - only optional modules that it will use if they're available.

2023-05-29 00:05 UTC, gran4 commented
> tl;dr I've also asked about it and been told no. It's annoying, but there are good reasons for it.

What should I do instead?

2023-05-29 04:28 UTC, pushfoo requested changes
> What should I do instead?

tl;dr Slow down and give yourself time to read & think. Also install mypy or pyright locally and use them before pushing since pyglet's CI doesn't run type checking yet.

The rest of the comment describes what I did to write the comments on your code changes.

### 1 / 3 : Take your time to read & experiment

Your recent PRs are more focused & concise, which is good.

However, you've started playing on hard mode by working on some of the oldest & most crucial library code in pyglet (2006). The code's age isn't a bad thing! The design works!

Trying to modernize this sort of codebase means you're taking on the responsibility of figuring out what's going on. This means:

1. Reading the code and experimenting with it
2. Reading any relevant doc, such as Python & library documentation
3. Reading supporting theory for things like shaders

For example, I usually have Python and library doc open at all times when I'm working. This includes while I was reviewing this PR. Sometimes, it's also necessary to search through old commits, bug reports, or PRs to understand what's wrong.

### 2 / 3 : Run type checking & unit tests before committing

After installing pyglet locally in dev mode, you can run unit tests locally with the following:

```console
pytest tests/unit
```
This will catch the sort of errors you've been seeing in the CI run, but without important benefits:
1. No waiting for the GitHub runner to become available & set up the environment.
2. If you're using an IDE like VSCode or PyCharm, file paths in exception traceback will be clickable links you can use to jump to the location of the error.

You should also set up linting and type checking locally because pyglet may not run thorough checking.
```console
pip install mypy
```

Afterwards, run it against specific files like this:
```console
mypy path/to/changed/file.py
```
I think ruff and pyright work the same way, but are much stricter by default.

### 3 / 3 : Do the research to answer your own questions when possible

I'm serious about this. Keep doc open in one window, code in the other. Search through  the GitHub issues of projects you use to look for relevant tickets, including closed ones.

A second monitor really helps if you can get one, even a cheap old 720p panel only big enough to fit a terminal.

2023-06-03 06:29 UTC, gran4 commented on pyglet/event.py
> +        Push a level onto the top of the handler stack, then attach zero or
Yeah

2023-06-03 06:30 UTC, gran4 commented on pyglet/clock.py
> +        :rtype: float
@pushfoo  It seems to be the same.

2023-06-06 01:17 UTC, benmoran56 requested changes

2023-06-06 01:17 UTC, benmoran56 commented on pyglet/event.py
> -        # A common problem in applications is having the wrong number of
This should be left as a block comment. It's an internal method that is not intended to be seen by users. The block comment contains notes for future programmers, not intended for user documentation.

2023-06-08 10:37 UTC, gran4 commented on pyglet/clock.py
> +    def __lt__(self, other: Union[_ScheduledIntervalItem, float]) -> bool:
look at line 106 `return self.next_ts < other`. other is a float

2023-06-28 11:56 UTC, gran4 commented on pyglet/clock.py
> +    def __lt__(self, other: Union[_ScheduledIntervalItem, float]) -> bool:
@benmoran56 I want you to see this if you have not already.

2023-09-16 00:33 UTC, closed without merging