Clarify intro and ffmpeg versions
pyglet/pyglet pull request #970
Opened 2023-10-13 03:57 UTC by pushfoo

### Changes

* Make it clear that pyglet is now optional in the intro
* Make intro generally clearer and more concise
* Add notes on FFmpeg and licensing

2023-10-13 17:00 UTC, caffeinepills requested changes
I submitted some areas I thought could use addressing. Other than that, looks good overall. Thanks

2023-10-16 17:37 UTC, pushfoo commented on doc/programming_guide/media.rst
> +In practice, WAV files always load and MP3 usually does. The exact
Reverted to be closer to the original.

2023-10-16 17:37 UTC, pushfoo commented on doc/programming_guide/media.rst
> +and encodings. Its main downsides are:
I've changed this to be closer to the original.

2023-10-16 17:37 UTC, pushfoo commented on doc/programming_guide/media.rst
> +It is impossible to list all its features here due to the large number
Updated to be closer to the original. :+1:

2023-10-16 19:28 UTC, caffeinepills commented on doc/programming_guide/media.rst
> +FFmpeg is best when you need to support the maximum number of formats
No GStreamer for video.

2023-10-16 19:31 UTC, caffeinepills approved these changes

2023-10-17 05:53 UTC, merged